image: maven:latest

stages:
  - deploy

cache:
  paths:
    - .m3/repository/
    - target/

deploy:
  stage: deploy
  only:
    - master
  script:
    - mvn clean install
    - mv target/*.jar mini.jar
    - scp -i /home/gitlab-runner/id_rsa target/*.jar root@134.209.96.234:/var/lib/pgsql/minipg/.
    - ssh -i /home/gitlab-runner/id_rsa root@134.209.96.234 /bin/su -c "/var/lib/pgsql/minipg/minipg.sh stop" - postgres
    - ssh -i /home/gitlab-runner/id_rsa root@134.209.96.234 /bin/su -c "/var/lib/pgsql/minipg/minipg.sh start" - postgres

    
